# Generated by Django 5.1.1 on 2024-10-04 04:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "welcome",
                    wagtail.fields.RichTextField(
                        default="\n<h2>Wir sind Ottilianer!</h2>\n<h4>Mehr als nur Schüler!</h4>\n<p>Das Rhabanus-Maurus-Gymnasium St. Ottilien hat mehr zu bieten als bloß Unterricht und Hausaufgaben. Neben zahlreichen AGs kann man sich auch bei der SMV oder bei den Schulsanitätern engagieren. Für musikalisch Begabte gibt es außerdem mehrere Chöre und Orchester. Doch auch der naturwissenschaftlich-technische Bereich kommt bei uns nicht\nzu kurz.</p>\n"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
