# Generated by Django 5.1.1 on 2024-10-04 12:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about",
            field=wagtail.fields.RichTextField(
                default="\n<h2>Über uns</h2>\n<p>Um die Frage auf dieses klassiche Fach auf dem Punkt zu bringen: Lateiner bohren keine dünnen Bretter! Habt ihr das verstanden ihr Hühner? Man kann auf diesem Blatt die Weichen zwischen Egling und Walleshausen erkennen.</p>\n<br>\n<p>Um die Frage auf dieses klassiche Fach auf dem Punkt zu bringen: Lateiner bohren keine dünnen Bretter! </p>\n<ul>\n<li>Holzweg</li>\n<li>Waldweg</li>\n<li>Wegweiser</li>\n</ul>\n"
            ),
        ),
    ]
