# Generated by Django 5.1.1 on 2024-10-04 12:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about",
            field=wagtail.fields.RichTextField(
                default="\n<h2>Über uns</h2>\n<p>Jarlsberg stilton macaroni cheese. Bavarian bergkase swiss macaroni cheese cut the cheese rubber cheese stilton edam stinking bishop. Danish fontina melted cheese bavarian bergkase melted cheese macaroni cheese st. agur blue cheese feta swiss. Cheddar jarlsberg fromage roquefort babybel croque monsieur taleggio.</p>\n<br>\n<p>Chalk and cheese cheesy feet cheese strings.</p>\n<ul>\n<li>Emmentaler</li>\n<li>Ricotta</li>\n<li>Mozarella</li>\n</ul>\n"
            ),
        ),
    ]
