# Generated by Django 5.1.1 on 2024-10-04 13:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about",
            field=wagtail.fields.RichTextField(
                default="\n<h2>Über uns</h2>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem voluptatem illo animi distinctio, similique cum obcaecati\nincidunt earum consequuntur modi repudiandae dolore beatae veritatis eos! Tempora quis ea dolorum nemo? Lorem ipsum\ndolor sit amet consectetur adipisicing elit. Maiores suscipit neque nesciunt, sint deleniti debitis iusto aliquam\nmollitia assumenda asperiores repudiandae vitae necessitatibus expedita iure. Cupiditate dolore dicta odit inventore.\n</p>\n<br>\n<p>Chalk and cheese cheesy feet cheese strings.</p>\n<br>\n<ul>\n<li>Lucius Livius Andronicus</li>\n<li>Vergil</li>\n<li>Titus Maccius Plautus</li>\n<li>Terenz</li>\n</ul>\n"
            ),
        ),
    ]
