# Generated by Django 5.1.1 on 2024-10-04 13:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_remove_diaryindexpage_intro"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarypage",
            name="author",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diarypage",
            name="image",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diarypage",
            name="date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Post date"
            ),
        ),
    ]
