name: ottilianer-v2
services:
  pocketbase:
    build:
      context: "."
      dockerfile: Dockerfile.pocketbase
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - "./pocketbase-data:/pb/pb_data"

  frontend:
    env_file:
      - example.env
    image: oven/bun:latest
    working_dir: /app
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./ottilianer:/app
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
