FROM node:20

WORKDIR /app

COPY ./package.json /app/package.json

RUN npm install -g pnpm

RUN pnpm install

COPY ./ /app

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "3000"]
