name: ottilianer-v2
services:
  pocketbase:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - "./backend/pb_data:/pb/pb_data"
      - "./backend/pb_hooks:/pb/pb_hooks"
    networks:
      - default

  nuxt:
    env_file:
      - .env.template
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    restart: unless-stopped
    networks:
      - default

  inbucket:
    image: "inbucket/inbucket:latest"
    ports:
      - "9000:9000"
      - "2500:2500"
      - "1100:1100"
    volumes:
      - "./inbucket:/data"
    restart: unless-stopped
    networks:
      - default

# network

networks:
  default:
    driver: bridge
