services:
  postgres:
    container_name: ottilianer-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    container_name: ottilianer-strapi
    image: oven/bun:latest
    working_dir: /app
    command: ["bun", "run", "develop"]
    volumes:
      - ./backend:/app
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      NODE_ENV: development
    depends_on:
      - postgres

  nuxt:
    container_name: ottilianer-nuxt
    image: oven/bun:latest
    working_dir: /app
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    environment:
      BACKEND_URL: http://strapi:1337

volumes:
  postgres_data:
